import {validate,csv} from './model.mjs';
import * as browserStore from './browser-store.mjs';
const schemas=await (await fetch('schemas.json')).json();
const form=document.querySelector('#application'), questions=document.querySelector('#questions'), version=document.querySelector('#version'),errors=document.querySelector('#errors'),receipt=document.querySelector('#receipt'),submit=document.querySelector('#submit');
const hostedServer=new URLSearchParams(location.search).get('storage')==='server';
if(hostedServer)document.querySelector('#adapter-note').textContent='Staging intake: synthetic data only. A receipt confirms database storage. Airtable synchronization may still be pending. If storage is not configured, submission is unavailable.';
const localServer=location.pathname.startsWith('/local-draft/');
if(localServer)document.querySelector('#adapter-note').textContent='Local test server: synthetic records are stored in SQLite on this computer. Nothing goes to Primordia or Airtable.';
const download=node('button','Download my draft');download.type='button';document.querySelector('.tools').append(download);
download.onclick=()=>{const url=URL.createObjectURL(new Blob([JSON.stringify({id,version:version.value,schema:schemas[version.value],answers:collect()},null,2)],{type:'application/json'}));const a=node('a');a.href=url;a.download='primordia-draft.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};
let id=crypto.randomUUID();let records=[];const drafts={};let currentVersion=version.value;let pending=false;
function node(tag,text){const e=document.createElement(tag);if(text!==undefined)e.textContent=text;return e;}
function persist(){try{sessionStorage.setItem('primordia-draft-'+(hostedServer?'server':'local'),JSON.stringify({id,version:version.value,answers:collect()}));}catch{document.querySelector('#adapter-note').textContent+=' Browser recovery is unavailable; keep this tab open or save a copy.';}}
function collect(){return Object.fromEntries(schemas[version.value].questions.map(q=>[q.key,form.elements.namedItem(q.key).value]));}
function render(){questions.replaceChildren();const groups=new Map();for(const q of schemas[version.value].questions){let group=groups.get(q.group);if(!group){group=node('fieldset');group.append(node('legend',q.group));groups.set(q.group,group);questions.append(group);}const box=node('div');box.className='field';const label=node('label');label.htmlFor=q.key;label.append(document.createTextNode(q.label+' '),node('small',q.required?'(required)':'(optional)'));const field=node(q.type==='textarea'?'textarea':'input');if(q.type!=='textarea')field.type=q.type;field.name=q.key;field.id=q.key;field.required=q.required;field.maxLength=q.maxLength;if(q.type==='number'){field.min='0.01';field.step='any';}if(q.key==='full_name')field.autocomplete='name';if(q.key==='email')field.autocomplete='email';field.value=drafts[version.value]?.[q.key]||'';const error=node('p');error.id=q.key+'-error';error.className='error';field.setAttribute('aria-describedby',error.id);box.append(label,field,error);group.append(box);}errors.hidden=true;receipt.textContent='';submit.disabled=false;}
function showErrors(list){errors.replaceChildren(node('p','Please correct the following:'));const ul=node('ul');for(const [key,message] of Object.entries(list)){const li=node('li');const link=node('a',message);link.href='#'+(key==='form'?'application':key);li.append(link);ul.append(li);const field=form.elements.namedItem(key);if(field){field.setAttribute('aria-invalid','true');document.getElementById(key+'-error').textContent=message;}}errors.append(ul);errors.hidden=false;errors.focus();}
async function refresh(){if(hostedServer){document.querySelector('.review').hidden=true;return;}records=localServer?await(await fetch('/api/test-records')).json():await browserStore.all();const target=document.querySelector('#records');target.replaceChildren();if(!records.length)target.append(node('p','No test records yet.'));for(const r of records){const details=node('details');details.append(node('summary',`${r.version} · ${r.id} · ${localServer?r.sync.state:'local only'}`));const dl=node('dl');for(const q of r.schema.questions)dl.append(node('dt',q.label),node('dd',r.answers[q.key]||'No answer'));details.append(dl);target.append(details);}}
form.addEventListener('submit',async event=>{event.preventDefault();if(pending)return;errors.hidden=true;form.querySelectorAll('[aria-invalid]').forEach(e=>e.removeAttribute('aria-invalid'));form.querySelectorAll('.error').forEach(e=>e.textContent='');const input={id,version:version.value,answers:collect(),honeypot:form.elements.website.value};const validation=validate(schemas[version.value],input);if(Object.keys(validation).length){showErrors(validation);return;}persist();pending=true;submit.disabled=true;version.disabled=true;receipt.textContent='Saving test record…';try{let record;if(localServer||hostedServer){const response=await fetch(hostedServer?'/.netlify/functions/application':'/api/test-submit',{method:'POST',headers:{'Content-Type':'application/json'},signal:AbortSignal.timeout(20000),body:JSON.stringify(input)});const body=await response.json();if(!response.ok)throw Object.assign(Error(body.message),{errors:body.errors});if(hostedServer&&(!body.accepted||body.id!==id))throw Error('The server did not return a valid receipt.');record=body;}else record=await browserStore.accept(schemas[version.value],input);receipt.textContent=hostedServer?`Saved to staging storage. Reference: ${record.id}. This synthetic test is not a grant application. Airtable synchronization may be pending.`:`Saved ${localServer?'on this computer':'in this browser'} only. Test reference: ${record.id}. This is not a grant application receipt.`;receipt.focus();await refresh();}catch(e){receipt.textContent='Not confirmed. Your answers remain here; retry with the same reference.';showErrors(e.errors||{form:e.message});}finally{pending=false;submit.disabled=false;version.disabled=false;}});
version.addEventListener('change',()=>{ // Preserve each version separately while testing schema changes.
 const old=schemas[currentVersion];drafts[currentVersion]=Object.fromEntries(old.questions.map(q=>[q.key,form.elements.namedItem(q.key)?.value||'']));currentVersion=version.value;id=crypto.randomUUID();render();persist();});
document.querySelector('#example').onclick=()=>{for(const q of schemas[version.value].questions)form.elements.namedItem(q.key).value=q.type==='email'?'synthetic@example.test':q.type==='number'?'100':q.key==='funding_currency'?'USD':'Synthetic example: '+q.label;};
document.querySelector('#new').onclick=()=>{if(pending)return;id=crypto.randomUUID();drafts[version.value]={};render();persist();};
document.querySelector('#refresh').onclick=()=>refresh().catch(e=>showErrors({form:e.message}));
for(const format of ['json','csv'])document.getElementById(format).onclick=async()=>{try{await refresh();const blob=new Blob([format==='json'?JSON.stringify(records,null,2):csv(records)],{type:format==='json'?'application/json':'text/csv'});const url=URL.createObjectURL(blob);const a=node('a');a.href=url;a.download='primordia-synthetic-history.'+format;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);}catch(e){showErrors({form:e.message});}};
try{const saved=JSON.parse(sessionStorage.getItem('primordia-draft-'+(hostedServer?'server':'local'))||'null');if(saved&&schemas[saved.version]){id=saved.id;version.value=saved.version;currentVersion=saved.version;drafts[saved.version]=saved.answers;}}catch{}
form.addEventListener('input',persist);
render();refresh().catch(e=>showErrors({form:e.message}));
